const state={countries:[],regions:[],cities:[],news:[],selected:{level:'world',country:null,region:null,city:null},filter:'ALL',autoRotate:CONFIG.AUTO_ROTATE,heatmap:CONFIG.NEWS_HEATMAP,globe:null,polygons:[],rotationTimer:null};
const $=id=>document.getElementById(id);
const FALLBACK=CONFIG.FALLBACK_IMAGE;

async function loadJSON(file){const r=await fetch(file,{cache:'no-store'});if(!r.ok)throw new Error(`${file}: HTTP ${r.status}`);return r.json()}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function timeAgo(value){const d=new Date(value),s=Math.max(0,Math.floor((Date.now()-d.getTime())/1000));if(s<60)return'Just now';const m=Math.floor(s/60);if(m<60)return`${m} min ago`;const h=Math.floor(m/60);if(h<24)return`${h} hour${h>1?'s':''} ago`;return`${Math.floor(h/24)} day${Math.floor(h/24)>1?'s':''} ago`}
function imageHTML(url,alt,cls=''){return`<img class="${cls}" src="${escapeHTML(url||FALLBACK)}" alt="${escapeHTML(alt)}" loading="lazy" onerror="this.onerror=null;this.src='${FALLBACK}'">`}
function currentNews(){let n=[...state.news];if(state.selected.level==='country'&&state.selected.country)n=n.filter(x=>x.country===state.selected.country.id);if(state.selected.level==='region'&&state.selected.region)n=n.filter(x=>x.country===state.selected.country?.id&&x.region===state.selected.region.id);if(state.selected.level==='city'&&state.selected.city)n=n.filter(x=>x.city===state.selected.city.name);if(state.filter!=='ALL')n=n.filter(x=>String(x.category||'').toUpperCase()===state.filter||state.filter==='BREAKING'&&x.breaking);return n.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt))}
function selectedTitle(){if(state.selected.level==='city')return state.selected.city.name;if(state.selected.level==='region')return state.selected.region.name;if(state.selected.level==='country')return state.selected.country.name;return'GLOBAL NEWS'}
function breadcrumb(){const b=$('breadcrumb');const parts=[`<button data-level="world">WORLD</button>`];if(state.selected.country)parts.push(`<button data-level="country">${escapeHTML(state.selected.country.name.toUpperCase())}</button>`);if(state.selected.region)parts.push(`<button data-level="region">${escapeHTML(state.selected.region.name.toUpperCase())}</button>`);if(state.selected.city)parts.push(`<button data-level="city">${escapeHTML(state.selected.city.name.toUpperCase())}</button>`);b.innerHTML=parts.join(' / ')}
function renderFilters(){const f=['ALL','BREAKING','POLITICS','BUSINESS','TECHNOLOGY','SCIENCE','SPORTS','ENTERTAINMENT','WEATHER','HEALTH','LOCAL'];$('filters').innerHTML=f.map(x=>`<button class="filter ${state.filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}
function renderNews(){const news=currentNews(),featured=news[0];$('panelTitle').textContent=selectedTitle();$('locationTitle').textContent=selectedTitle();breadcrumb();renderFilters();$('backBtn').hidden=state.selected.level==='world';if(!featured){$('featuredNews').innerHTML=`<div class="meta">No stories found for this location/filter.</div>`;$('newsList').innerHTML='';return}$('featuredNews').innerHTML=`<article class="featured">${imageHTML(featured.image,featured.title)}<div class="featured-body"><div class="category ${featured.breaking?'breaking':''}">${featured.breaking?'🔴 BREAKING · ':''}${escapeHTML(featured.category||'NEWS')}</div><h3>${escapeHTML(featured.title)}</h3><p>${escapeHTML(featured.description)}</p><div class="meta">${escapeHTML(featured.source||'WorldLens Demo')} · ${timeAgo(featured.publishedAt)}</div><a class="read" href="${escapeHTML(featured.url||'#')}" target="_blank" rel="noopener noreferrer">READ FULL STORY →</a></div></article>`;$('newsList').innerHTML=news.slice(1,8).map(n=>`<article class="news-card">${imageHTML(n.image,n.title)}<div><div class="category ${n.breaking?'breaking':''}">${n.breaking?'🔴 BREAKING · ':''}${escapeHTML(n.category||'NEWS')}</div><h4>${escapeHTML(n.title)}</h4><p>${escapeHTML(n.description)}</p><div class="meta">${escapeHTML(n.source||'WorldLens Demo')} · ${timeAgo(n.publishedAt)}</div><a class="read" href="${escapeHTML(n.url||'#')}" target="_blank" rel="noopener noreferrer">READ →</a></div></article>`).join('')}
function camera(lat,lng,alt=1.5){if(!state.globe)return;state.globe.pointOfView({lat,lng,alt},1200);interactionPause()}
function interactionPause(){if(state.rotationTimer)clearTimeout(state.rotationTimer);if(state.autoRotate)state.rotationTimer=setTimeout(startRotation,3000)}
function startRotation(){if(!state.autoRotate||!state.globe)return;state.globe.controls().autoRotate=true;state.globe.controls().autoRotateSpeed=.35}
function stopRotation(){if(state.globe)state.globe.controls().autoRotate=false}
function selectWorld(){state.selected={level:'world',country:null,region:null,city:null};renderNews();camera(20,0,2.4)}
function selectCountry(c){if(!c)return;state.selected={level:'country',country:c,region:null,city:null};renderNews();camera(c.lat,c.lng,1.35)}
function selectRegion(r){if(!r)return;const c=state.countries.find(x=>x.id===r.country);state.selected={level:'region',country:c||null,region:r,city:null};renderNews();camera(r.lat,r.lng,.55)}
function selectCity(city){if(!city)return;const c=state.countries.find(x=>x.id===city.country);const r=state.regions.find(x=>x.id===city.region);state.selected={level:'city',country:c||null,region:r||null,city};renderNews();camera(city.lat,city.lng,.22)}
function search(q){q=q.trim().toLowerCase();if(!q){$('searchResults').classList.remove('show');return}const out=[];state.countries.filter(x=>x.name.toLowerCase().includes(q)).slice(0,4).forEach(x=>out.push({type:'Country',name:x.name,item:x}));state.regions.filter(x=>x.name.toLowerCase().includes(q)).slice(0,4).forEach(x=>out.push({type:'Region',name:x.name,item:x}));state.cities.filter(x=>x.name.toLowerCase().includes(q)).slice(0,6).forEach(x=>out.push({type:'City',name:x.name,item:x}));$('searchResults').innerHTML=out.slice(0,8).map((x,i)=>`<button class="search-result" data-index="${i}"><b>📍 ${escapeHTML(x.name)}</b><small>${x.type}</small></button>`).join('');$('searchResults').classList.toggle('show',out.length>0);$('searchResults')._items=out}
function initGlobe(){if(typeof Globe!=='function')throw new Error('Globe.gl failed to load');state.globe=Globe()(document.getElementById('globeViz')).backgroundColor('#02050b').globeImageUrl(CONFIG.GLOBE_IMAGE).bumpImageUrl(CONFIG.BUMP_IMAGE).showAtmosphere(true).atmosphereColor('#5e9cff').atmosphereAltitude(.16).pointsData([]).pointLat('lat').pointLng('lng').pointColor('color').pointRadius('radius').pointAltitude(.015).pointLabel('label').onPointClick(p=>{const c=state.cities.find(x=>x.name===p.city);if(c)selectCity(c)});state.globe.controls().enableDamping=true;state.globe.controls().dampingFactor=.08;startRotation();const resize=()=>{if(state.globe){const el=document.getElementById('globeViz');state.globe.width(el.clientWidth).height(el.clientHeight)}};window.addEventListener('resize',resize);setTimeout(resize,100)}
async function loadPolygons(){try{const topo=await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json').then(r=>{if(!r.ok)throw new Error('boundary HTTP '+r.status);return r.json()});const features=topojson.feature(topo,topo.objects.countries).features;state.polygons=features;if(!state.globe)return;state.globe.polygonsData(features).polygonLabel(d=>`<b>${escapeHTML(d.properties?.name||d.properties?.NAME||'Country')}</b>`).polygonCapColor(d=>{const n=(d.properties?.name||d.properties?.NAME||'').toLowerCase();return n.includes('india')?'rgba(55,130,240,.38)':'rgba(55,105,180,.16)'}).polygonSideColor(()=> 'rgba(60,100,170,.18)').polygonStrokeColor(()=> 'rgba(120,170,255,.45)').polygonAltitude(.005).onPolygonClick(d=>{const name=(d.properties?.name||d.properties?.NAME||'').toLowerCase();const aliases={'united states of america':'United States','usa':'United States','united states':'United States','united kingdom':'United Kingdom','russia':'Russia'};const wanted=aliases[name]||Object.keys(aliases).find(k=>name===k)?aliases[name]:d.properties?.name||d.properties?.NAME;const c=state.countries.find(x=>x.name.toLowerCase()===String(wanted).toLowerCase());if(c)selectCountry(c);else interactionPause()}).onPolygonHover(d=>{if(state.globe)state.globe.polygonAltitude(x=>x===d?.[0]?.__data__?.feature?.properties?.name?.toLowerCase()?0.02:.005)}).onPolygonClick(()=>interactionPause())}catch(e){console.warn('Boundary data unavailable:',e.message)}}
function renderMarkers(){if(!state.globe)return;const markers=state.cities.map(c=>{const count=state.news.filter(n=>n.city===c.name).length;return{...c,radius:.22+count*.045,color:count>2?'#ff4f5f':'#ffad45',label:`<b>${escapeHTML(c.name)}</b><br>${count} recent stories`}});state.globe.pointsData(markers);state.globe.pointColor(p=>state.heatmap?p.color:'#5da2ff')}
async function init(){try{$('loadingText').textContent='Loading news data...';const [countries,regions,cities,news]=await Promise.all([loadJSON('countries.json'),loadJSON('regions.json'),loadJSON('cities.json'),loadJSON('news.json')]);state.countries=countries;state.regions=regions;state.cities=cities;state.news=news;renderNews();$('loadingText').textContent=`${news.length} demo stories loaded`;try{initGlobe();renderMarkers();await loadPolygons()}catch(globeError){console.warn('Globe unavailable, news panel remains active:',globeError)}$('loading').classList.add('hidden')}catch(e){console.error('WorldLens data error:',e);$('loadingText').textContent='News data could not be loaded';$('errorBox').hidden=false;$('loading').classList.add('hidden');$('featuredNews').innerHTML='<div class="meta">Unable to load news.json. Please run the project from a web server, not file://.</div>'}}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){state.filter=f.dataset.filter;renderNews();return}const crumb=e.target.closest('#breadcrumb button');if(crumb){if(crumb.dataset.level==='world')selectWorld();else if(crumb.dataset.level==='country')selectCountry(state.selected.country);else if(crumb.dataset.level==='region')selectRegion(state.selected.region);return}const sr=e.target.closest('.search-result');if(sr){const x=$('searchResults')._items[Number(sr.dataset.index)];$('searchResults').classList.remove('show');$('searchInput').value=x.name;if(x.type==='Country')selectCountry(x.item);else if(x.type==='Region')selectRegion(x.item);else selectCity(x.item)}});
$('searchInput').addEventListener('input',e=>search(e.target.value));
$('zoomIn').onclick=()=>{if(!state.globe)return;const p=state.globe.pointOfView();state.globe.pointOfView({...p,altitude:Math.max(.15,p.altitude*.75)},400);interactionPause()};
$('zoomOut').onclick=()=>{if(!state.globe)return;const p=state.globe.pointOfView();state.globe.pointOfView({...p,altitude:Math.min(4,p.altitude*1.3)},400);interactionPause()};
$('resetBtn').onclick=selectWorld;
$('backBtn').onclick=()=>{if(state.selected.level==='city')selectRegion(state.selected.region);else if(state.selected.level==='region')selectCountry(state.selected.country);else selectWorld()};
$('rotateBtn').onclick=()=>{state.autoRotate=!state.autoRotate;$('rotateBtn').textContent=`AUTO ROTATE: ${state.autoRotate?'ON':'OFF'}`;state.autoRotate?startRotation():stopRotation()};
$('heatBtn').onclick=()=>{state.heatmap=!state.heatmap;$('heatBtn').textContent=`HEATMAP: ${state.heatmap?'ON':'OFF'}`;renderMarkers()};
$('fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();
$('themeBtn').onclick=()=>document.body.classList.toggle('light');
$('retryBtn').onclick=()=>location.reload();
window.addEventListener('pointerdown',()=>{stopRotation();interactionPause()},{passive:true});
init();